#!/bin/sh

# script/bootstrap: Set up project dependencies

set -e

cd "$(dirname "$0")/.."

echo "Installing dependencies..."

yarn --dev

cd server
yarn

cd ..

cd client
yarn

cd ..

cd scanner
yarn
